#!/usr/bin/env zsh

link() {
	local src="$(pwd)/$1"
	local dst="$HOME/.$1"
	if [[ -f $dst || -L $dst ]]; then
		echo "[INFO] \"$dst\" already exists, skip linking \"$src\"."
		return
	fi
	echo "[INFO] linking $src to $dst."
	ln -s $src $dst
}

install_vim_plugged_manager() {
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

clone_zsh_plugins() {
	# https://github.com/zsh-users/zsh-syntax-highlighting
	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
	       ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting || \
	echo "[INFO] Already cloned zsh-syntax-highlighting."

	# https://github.com/zsh-users/zsh-completions
	git clone https://github.com/zsh-users/zsh-completions \
		${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions || \
	echo "[INFO] Already cloned zsh-completions."


}

main() {
	install_vim_plugged_manager
	clone_zsh_plugins
	for config in zshrc vimrc; do
		link $config
	done

}

main "$@"
