#!/usr/bin/env bash

TOP_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." >/dev/null 2>&1 && pwd)"

LINKED_CONFIGS=()

link() {
	local src="$1"
	local dst="$HOME/.$(basename $1)"
	local force_update=${2:-false}
	if [[ -f $dst || -L $dst ]]; then
		echo "[WRNING] \"$dst\" already exists, backup as \"$dst.backup\"."
                mv "$dst" "$dst.backup"
	fi
	echo "[INFO] linking $src to $dst."
	ln -s $src $dst
	LINKED_CONFIGS+=$dst
}

main() {
	for config in $TOP_DIR/configs/* ; do
                pre=$TOP_DIR/scripts/pre_$(basename $config)
                if [[ -f $pre ]]; then
                        echo "[INFO] Executing $pre"
                        $pre
                fi
                link $config
	done

	if (( ${#LINKED_CONFIGS[*]} > 0 )); then
		echo "[INFO] Following config files are linked this time. Source them if necessary."
		printf "%s\n" "${LINKED_CONFIGS[@]}"
	fi
}

main "$@"
