#!/usr/bin/env bash

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"

LINKED_CONFIGS=()

link() {
	local src="$1"
	local dst="$HOME/.$(basename $1)"
	local force_update=${2:-false}
	if [[ -f $dst || -L $dst ]]; then
		if [[ $force_update == true ]]; then
			echo "[WRNING] \"$dst\" already exists, backup as \"$dst.backup\"."
		else
			echo "[INFO] \"$dst\" already exists, skip linking \"$src\"."
		fi
		return
	fi
	echo "[INFO] linking $src to $dst."
	ln -s $src $dst
	LINKED_CONFIGS+=$dst
}

main() {
	local force_update=${1:-false}
	for config in $SCRIPTS_DIR/../* ; do
		if [[ -f $config && $config != *README.md* ]]; then
			pre=$SCRIPTS_DIR/pre_$(basename $config)
			if [[ -f $pre ]]; then
				echo "[INFO] Executing $pre"
				$pre
			fi
			link $config $force_update
		fi
	done

	if (( ${#LINKED_CONFIGS[*]} > 0 )); then
		echo "[INFO] Following config files are linked. Source them if necessary."
		printf "%s\n" "${LINKED_CONFIGS[@]}"
	fi
}

main "$@"
