#!/usr/bin/env zsh

# Install oh-my-zsh
# https://ohmyz.sh/#install
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# https://github.com/zsh-users/zsh-syntax-highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
	${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting > /dev/null 2>&1 || \
    echo "[INFO] Already cloned zsh-syntax-highlighting."

# https://github.com/zsh-users/zsh-completions
git clone https://github.com/zsh-users/zsh-completions \
	${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions > /dev/null 2>&1 || \
    echo "[INFO] Already cloned zsh-completions."

# https://github.com/zsh-users/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions \
	${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions > /dev/null 2>&1 || \
    echo "[INFO] Already cloned zsh-autosuggestions."

