#!/usr/bin/env zsh

SCRIPTS_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

link() {
	local src="$(pwd)/$1"
	local dst="$HOME/.$1"
	if [[ -f $dst || -L $dst ]]; then
		echo "[INFO] \"$dst\" already exists, skip linking \"$src\"."
		return
	fi
	echo "[INFO] linking $src to $dst."
	ln -s $src $dst
}

install_vim_plugged_manager() {
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    		https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

clone_zsh_plugins() {
	# https://github.com/zsh-users/zsh-syntax-highlighting
	git clone https://github.com/zsh-users/zsh-syntax-highlighting.git \
	       ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting || \
	echo "[INFO] Already cloned zsh-syntax-highlighting."

	# https://github.com/zsh-users/zsh-completions
	git clone https://github.com/zsh-users/zsh-completions \
		${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions || \
	echo "[INFO] Already cloned zsh-completions."
}


main() {
	for config in $SCRIPTS_DIR/../* ; do
		if [[ -f $config && $config != "README.md" ]]; then
			if [[ -f $SCRIPTS_DIR/pre_$config ]]; then
				$SCRIPTS_DIR/pre_$config
			fi
			link $config
		fi
	done

}

main "$@"
